[package]
name = "kissat-rs"
version = "0.1.0"
authors = ["Florian Sextl <sextl@in.tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-try-from-primitive = "1.0.0"
kissat-sys = { path = "./kissat-sys", version = "0.1.0" }
thiserror = "1.0.24"
