[package]
name = "kissat-sys"
version = "0.1.0"
description = " Low-level Rust bindings for the Kissat SAT solver."
license = "MIT"
author = ["Florian Sextl <sextl@in.tum.de>"]
repository = "https://github.com/firefighterduck/kissat-rs"
edition = "2018"
readme = "README.md"
categories = ["external-ffi-bindings"]

[build-dependencies]
bindgen = "0.58.1"
